import { Link, useParams } from "wouter";
const INTEGRATIONS: Record<string, { name: string; category: string; description: string; useCases: string[]; benefits: string[] }> = {
  "make-integromat": { name: "Make (Integromat)", category: "Automation Platform", description: "Make is the primary automation platform used by Barrana.ai for complex, multi-step workflows. It connects over 1,000 business tools and handles conditional logic, data transformation, and error handling with a visual workflow builder.", useCases: ["Multi-step client intake workflows", "Document collection and tracking systems", "Lead routing with conditional logic", "CRM data synchronization", "Invoice generation triggers"], benefits: ["Visual workflow builder makes complex logic manageable", "Handles errors gracefully with retry logic", "Supports complex data transformations", "Detailed execution logs for auditing", "Cost-effective for high-volume automations"] },
  "zapier": { name: "Zapier", category: "Automation Platform", description: "Zapier connects over 5,000 apps and is used for simpler automation workflows. It is ideal for straightforward trigger-action automations where the logic is linear and the tools are well-supported.", useCases: ["Simple lead notification workflows", "Form submission to CRM creation", "Calendar event to task creation", "Email trigger to Slack notification", "Payment received to invoice logging"], benefits: ["Largest app library of any automation platform", "Easy to set up for simple workflows", "Reliable for straightforward integrations", "Good documentation and support"] },
  "hubspot": { name: "HubSpot", category: "CRM", description: "HubSpot is a popular CRM for small and medium businesses. Barrana.ai builds automation that creates, updates, and manages HubSpot records automatically from form submissions, emails, and other triggers.", useCases: ["Automatic lead record creation from form submissions", "Pipeline stage updates based on client actions", "Automated email sequences from CRM triggers", "Task creation for follow-up actions", "Deal tracking and reporting automation"], benefits: ["Free tier available for small businesses", "Strong email automation capabilities", "Good integration with most business tools", "Detailed contact and deal tracking"] },
  "jobber": { name: "Jobber", category: "Field Service", description: "Jobber is field service management software for contractors and service businesses. Barrana.ai integrates Jobber with lead capture forms, quote systems, and payment processors to create a complete lead-to-payment automation system.", useCases: ["Lead form to Jobber client creation", "Quote generation from intake form data", "Job scheduling automation", "Invoice generation on job completion", "Payment reminder sequences"], benefits: ["Purpose-built for contractors and field service businesses", "Strong mobile app for on-site use", "Integrated quoting, scheduling, and invoicing", "Good integration with payment processors"] },
  "quickbooks": { name: "QuickBooks", category: "Accounting", description: "QuickBooks is the most common accounting software for small businesses in Canada. Barrana.ai builds automation that creates invoices, records payments, and syncs client data with QuickBooks automatically.", useCases: ["Automatic invoice creation on project completion", "Payment recording from payment processor webhooks", "Client record synchronization with CRM", "Expense categorization automation", "Financial report generation triggers"], benefits: ["Standard accounting software for Canadian small businesses", "Strong integration ecosystem", "Good support for Canadian tax requirements", "Reliable API for automation"] },
  "calendly": { name: "Calendly", category: "Scheduling", description: "Calendly is online scheduling software used for appointment booking automation. Barrana.ai integrates Calendly with CRM systems, reminder sequences, and intake workflows to create a complete booking-to-onboarding system.", useCases: ["New booking to CRM lead creation", "Booking confirmation to intake form delivery", "Appointment reminder sequence trigger", "No-show detection and rebooking automation", "Post-appointment follow-up sequences"], benefits: ["Easy for clients to use without an account", "Integrates with Google and Microsoft calendars", "Supports team scheduling and routing", "Good webhook support for automation"] },
  "jotform": { name: "Jotform", category: "Forms", description: "Jotform is an online form builder used for intake forms, document requests, and lead capture. Barrana.ai builds automation that processes Jotform submissions and routes data to the appropriate systems.", useCases: ["Client intake form processing", "Document upload collection", "Lead capture form processing", "Survey and feedback collection", "Conditional form logic for qualification"], benefits: ["Powerful conditional logic for complex forms", "Good file upload capabilities for document collection", "HIPAA-compliant option for healthcare", "Strong integration with automation platforms"] },
  "gohighlevel": { name: "GoHighLevel", category: "CRM", description: "GoHighLevel is an all-in-one CRM and marketing automation platform. Barrana.ai builds custom automation workflows within GoHighLevel for lead management, client communication, and pipeline management.", useCases: ["Complete lead management pipeline", "SMS and email follow-up sequences", "Appointment booking and management", "Client communication automation", "Review request sequences"], benefits: ["All-in-one platform reduces tool complexity", "Strong SMS automation capabilities", "Good pipeline management features", "White-label option for agencies"] },
  "twilio": { name: "Twilio", category: "Communications", description: "Twilio is a communications platform used for SMS automation. Barrana.ai uses Twilio for appointment reminders, lead response notifications, and two-way SMS communication workflows.", useCases: ["Appointment reminder SMS sequences", "Lead response SMS notifications", "Two-way SMS intake conversations", "Payment reminder SMS", "After-hours inquiry capture"], benefits: ["Reliable SMS delivery infrastructure", "Supports two-way SMS conversations", "Good Canadian number availability", "Detailed delivery reporting"] },
  "google-workspace": { name: "Google Workspace", category: "Productivity", description: "Google Workspace includes Gmail, Calendar, Drive, Sheets, and Docs. Barrana.ai builds automation that integrates Google Workspace with CRM systems, form processors, and project management tools.", useCases: ["Gmail trigger to CRM record creation", "Calendar event to task creation", "Google Sheets as a data source for automation", "Drive file organization automation", "Google Forms to CRM integration"], benefits: ["Standard productivity suite for many small businesses", "Strong API for automation", "Good integration with most business tools", "Familiar interface for staff"] },
};
export default function IntegrationDetail() {
  const params = useParams<{ slug: string }>();
  const int = INTEGRATIONS[params.slug || ""];
  if (!int) return <div className="min-h-screen bg-white pt-24"><div className="container py-16"><h1 className="text-2xl font-bold mb-4" style={{ color: "#1F2937" }}>Integration not found</h1><Link href="/integrations" className="btn-secondary">Back to Integrations</Link></div></div>;
  return (
    <div className="min-h-screen bg-white">
      <section className="hero-light pt-24 pb-12">
        <div className="container">
          <div className="breadcrumb"><Link href="/">Home</Link><span className="breadcrumb-sep">/</span><Link href="/integrations">Integrations</Link><span className="breadcrumb-sep">/</span><span>{int.name}</span></div>
          <div className="max-w-3xl"><div className="tag-teal mb-4">{int.category}</div><h1 className="font-extrabold mb-4" style={{ color: "#1F2937" }}>{int.name} Integration</h1><p className="text-lg leading-relaxed" style={{ color: "#6B7280" }}>{int.description}</p></div>
        </div>
      </section>
      <section className="py-12">
        <div className="container">
          <div className="max-w-3xl grid md:grid-cols-2 gap-8">
            <div className="p-6 rounded-2xl border" style={{ borderColor: "rgba(26,82,118,0.1)", backgroundColor: "#F7F9FC" }}>
              <h2 className="font-bold mb-4" style={{ color: "#283891" }}>Common Use Cases</h2>
              <ul className="space-y-2">{int.useCases.map((uc, i) => <li key={i} className="flex items-start gap-2 text-sm" style={{ color: "#374151" }}><span className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ backgroundColor: "#7E0F4A" }} />{uc}</li>)}</ul>
            </div>
            <div className="p-6 rounded-2xl border" style={{ borderColor: "rgba(26,82,118,0.1)", backgroundColor: "#F7F9FC" }}>
              <h2 className="font-bold mb-4" style={{ color: "#283891" }}>Why We Use It</h2>
              <ul className="space-y-2">{int.benefits.map((b, i) => <li key={i} className="flex items-start gap-2 text-sm" style={{ color: "#374151" }}><span className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ backgroundColor: "#059669" }} />{b}</li>)}</ul>
            </div>
          </div>
          <div className="max-w-3xl mt-10 p-8 rounded-2xl" style={{ background: "linear-gradient(135deg, #1E2B6E, #283891)" }}>
            <h3 className="text-xl font-bold text-white mb-3">Want to Integrate {int.name} with Your Business?</h3>
            <p className="mb-6" style={{ color: "rgba(255,255,255,0.7)" }}>Book a free Automation Audit and we will design an integration plan for your specific workflows.</p>
            <Link href="/contact" className="btn-primary">Book Free Audit</Link>
          </div>
        </div>
      </section>
    </div>
  );
}
