import { Link, useParams } from "wouter";
const INSIGHTS: Record<string, { title: string; tag: string; readTime: string; intro: string; sections: { heading: string; body: string }[] }> = {
  "response-time-systems-problem": { title: "Why Response Time Is a Systems Problem, Not a Sales Problem", tag: "Lead Response", readTime: "6 min read", intro: "Most GTA service businesses lose leads not because their prices are wrong or their pitch is weak, but because a human being has to notice the inquiry and choose to respond. When response time averages four to eight hours, a third of your qualified leads have already booked with someone else. This is a systems problem - and systems problems have systems solutions.", sections: [] },
  "hidden-cost-manual-intake": { title: "The Hidden Cost of Manual Client Intake", tag: "Operations", readTime: "5 min read", intro: "When intake is manual, the real cost isn't the 45 minutes per client - it's the error rate, the lag, and the staff capacity absorbed by data entry instead of value-adding work.", sections: [] },
  "admin-hours-annual-cost": { title: "What Your Admin Hours Actually Cost Per Year", tag: "ROI Analysis", readTime: "4 min read", intro: "At $25/hour, 15 admin hours per week is $19,500 annually - and that's before accounting for the opportunity cost of staff doing coordination instead of billable work.", sections: [] },
  "why-follow-up-fails": { title: "Why Follow-Up Fails (And How to Fix It Systematically)", tag: "Lead Management", readTime: "5 min read", intro: "Manual follow-up fails for a simple reason: it depends on a person remembering to do it while managing everything else. The fix isn't discipline - it's removing the human dependency.", sections: [] },
  "control-layer-boundaries": { title: "The Control Layer: Why Every Automation Needs Boundaries", tag: "Governance", readTime: "6 min read", intro: "Automation without a control layer is a liability. Stop-loss logic, escalation paths, and audit trails aren't optional extras - they're what separates a reliable system from a reckless one.", sections: [] },
  "immigration-intake-field-report": { title: "Intake Automation for Immigration Firms: A Field Report", tag: "Immigration", readTime: "7 min read", intro: "How an immigration consulting firm in Mississauga reduced intake time from 50 minutes to under 5 - without changing their process, just removing the manual steps from their staff's plate.", sections: [] },
  "immigration-consultant-automation": { title: "Automation for Immigration Consultants: What Works and What Does Not", tag: "Immigration", readTime: "9 min read", intro: "Immigration consulting firms face a specific automation challenge: high-volume client intake, complex document requirements, strict regulatory deadlines, and the need for precise file tracking. The good news is that most of the operational bottlenecks in immigration practice are highly automatable. The compliance-sensitive parts - professional advice, strategy, and judgment - are not, and should not be.", sections: [{ heading: "What Works Well", body: "Lead capture and qualification, client intake form delivery and CRM record creation, document checklist delivery based on visa type, automated document reminders, appointment scheduling, status update notifications, and post-case satisfaction surveys all automate well in immigration practice." }, { heading: "What Does Not Work", body: "Automated systems should never provide immigration advice, assess eligibility, or communicate on substantive file matters without human review. Every automated communication should be clearly identified as administrative, not advisory. Escalation logic must route to a human consultant for any substantive inquiry." }, { heading: "Compliance Considerations", body: "PIPEDA applies to all client personal information. Document collection systems must have clear data retention and deletion policies. All automated communications should be reviewed by a regulated consultant before deployment." }] },
  "accounting-firm-automation": { title: "Automation for Accounting Firms: The Document Chase Problem", tag: "Accounting", readTime: "8 min read", intro: "Every accounting firm has the same problem: clients who do not send their documents on time. Staff spend hours every week sending reminder emails, following up by phone, and manually tracking what has and has not been received. This is the highest-ROI automation opportunity for most accounting practices.", sections: [{ heading: "The Document Chase Cycle", body: "The typical document collection cycle: send an email request, wait, send a follow-up, wait, call the client, receive partial documents, send another request for the missing items, wait. This cycle repeats for every client, every engagement period. Automation eliminates it." }, { heading: "How Document Collection Automation Works", body: "When a new engagement is confirmed, the system automatically sends a document request checklist specific to the service type. The system tracks which documents have been received and sends automated reminders every 48 hours for outstanding items. Staff are notified when all documents are received and ready for review." }, { heading: "What Results to Expect", body: "Accounting firms that implement document collection automation typically see staff time on document chasing reduced by 80 to 90 percent, document collection cycles shortened by 50 to 65 percent, and staff able to focus on the work that requires their expertise instead of administrative follow-up." }] },
  "contractor-lead-automation": { title: "Lead Automation for Contractors: Why Response Time Is Everything", tag: "Contractors", readTime: "7 min read", intro: "Contractors lose more qualified leads to slow response time than to price. A homeowner who submits a quote request is typically contacting 3 to 5 contractors simultaneously. The first contractor to respond with a professional, helpful message wins the appointment. Most contractors respond in 4 to 8 hours. Automation responds in 90 seconds.", sections: [{ heading: "The Response Time Problem", body: "A contractor on a job site cannot respond to lead inquiries in real time. By the time they check their phone or email, the lead has already heard back from a competitor. This is not a motivation problem - it is a structural problem that automation solves." }, { heading: "What Lead Automation Does", body: "When a lead submits a form, the system sends an immediate acknowledgment, asks 2 to 3 qualification questions, and sends a calendar link to book a site visit. The contractor receives a notification with the lead details. If the lead does not book, the system follows up automatically." }, { heading: "The Competitive Advantage", body: "Most contractors in the GTA do not have automated lead response. A contractor who responds within 90 seconds, 24 hours a day, 7 days a week, has a significant competitive advantage - especially for after-hours and weekend inquiries." }] },
  "physiotherapy-no-show-reduction": { title: "No-Show Reduction for Physiotherapy Clinics: A Systems Approach", tag: "Healthcare", readTime: "6 min read", intro: "A physiotherapy clinic with a 20 percent no-show rate is losing 20 percent of its appointment capacity every week. Automated reminder sequences consistently reduce no-show rates to 8 to 12 percent - a 40 to 50 percent improvement that directly increases revenue without adding any new clients.", sections: [{ heading: "The No-Show Problem", body: "Patients forget appointments. Life gets busy. Without a reminder, a significant percentage of booked appointments simply do not show up. Manual reminder calls are time-consuming and inconsistent. Automated reminders are consistent, timely, and require no staff effort." }, { heading: "The Optimal Reminder Sequence", body: "The highest-performing reminder sequences include: a 48-hour reminder with preparation instructions, a 24-hour confirmation request that asks the patient to confirm or reschedule, and a 2-hour day-of reminder with location and parking information. Each message should include an easy rebooking option." }, { heading: "What Results to Expect", body: "Clinics that implement automated reminder sequences typically see no-show rates drop from 15 to 25 percent to 8 to 12 percent within 30 days of deployment. For a clinic with 100 appointments per week, this represents 7 to 13 additional attended appointments per week." }] },
  "law-firm-intake-automation": { title: "Client Intake Automation for Law Firms: Compliance and Efficiency", tag: "Legal", readTime: "10 min read", intro: "Law firms face a specific intake automation challenge: the need to automate efficiency while maintaining compliance with professional responsibility obligations, conflict check requirements, and engagement letter standards. This is achievable - but requires careful design.", sections: [{ heading: "What Can Be Automated", body: "Initial inquiry acknowledgment, intake form delivery and completion tracking, conflict check data collection, engagement letter delivery and e-signature collection, retainer invoice generation, and client portal access setup all automate well in legal practice." }, { heading: "Conflict Check Integration", body: "Intake automation can collect the information needed for conflict checks (client name, opposing parties, matter type) and route it to the appropriate person for review before the engagement is confirmed. The system holds the intake process pending conflict clearance." }, { heading: "Professional Responsibility Considerations", body: "Automated communications should be clearly administrative, not advisory. No automated system should provide legal advice, assess the merits of a matter, or communicate on substantive legal issues. All substantive client communications require human review and approval." }] },
};
export default function OperatorInsightArticle() {
  const params = useParams<{ slug: string }>();
  const article = INSIGHTS[params.slug || ""];
  if (!article) return <div className="min-h-screen bg-white pt-24"><div className="container py-16"><h1 className="text-2xl font-bold mb-4" style={{ color: "#1F2937" }}>Article not found</h1><Link href="/operator-insights" className="btn-secondary">Back to Operator Insights</Link></div></div>;
  return (
    <div className="min-h-screen bg-white">
      <section className="hero-light pt-24 pb-12">
        <div className="container">
          <div className="breadcrumb"><Link href="/">Home</Link><span className="breadcrumb-sep">/</span><Link href="/operator-insights">Operator Insights</Link><span className="breadcrumb-sep">/</span><span>{article.tag}</span></div>
          <div className="max-w-3xl"><div className="tag-blue mb-4">{article.tag}</div><h1 className="font-extrabold mb-4" style={{ color: "#1F2937" }}>{article.title}</h1><p className="text-sm" style={{ color: "#6B7280" }}>{article.readTime}</p></div>
        </div>
      </section>
      <section className="py-12">
        <div className="container">
          <div className="max-w-3xl">
            <div className="aeo-block mb-10"><div className="aeo-label"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Summary</div><p>{article.intro}</p></div>
            {article.sections.map((s, i) => <div key={i} className="mb-8"><h2 className="text-xl font-bold mb-3" style={{ color: "#283891" }}>{s.heading}</h2><p className="leading-relaxed" style={{ color: "#374151" }}>{s.body}</p></div>)}
            <div className="mt-12 p-8 rounded-2xl" style={{ background: "linear-gradient(135deg, #1E2B6E, #283891)" }}><h3 className="text-xl font-bold text-white mb-3">Ready to Implement This?</h3><p className="mb-6" style={{ color: "rgba(255,255,255,0.7)" }}>Book a free Automation Audit and we will map this for your specific business.</p><Link href="/contact" className="btn-primary">Book Free Audit</Link></div>
          </div>
        </div>
      </section>
    </div>
  );
}
